[tool.poetry]
name = "GetHired"
version = "0.1.0"
description = "Job search automation ADK Agent. Designed to optimize and automate the job search process. It uses keywords from user and performs tailored job searches through google, and gathers all relevant listings, conduct research on the company, tailor resume, and prepare for application submission."
authors = [
    "Aaliyah Johnson, La'Kaleigh Harris <neoaxiom@gmail.com>"
]
readme = "../README.md"

[tool.poetry.dependencies]
python = "^3.11"
google-adk = "^1.2.1"
google-genai = "1.19.0"
google-cloud-bigquery = "^3.31.0"
absl-py = "^2.2.2"
google-cloud-aiplatform =">=1.95.1"
pytest = "^8.3.5"
pillow = "^11.1.0"
npx = "^0.1.6"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
